# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test_pwd123
      POSTGRES_DB: blogy
    ports:
      - 5435:5432

  test_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test_pwd123
      POSTGRES_DB: test
    ports:
      - 5434:5432
